---
title: "HW1"
author: "Pat Byrne"
date: "2/17/2020"
output: html_document
---

```{r setup, include=FALSE}
# Clear global environment
rm(list = ls()) 
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# Attach packages
library(tidyverse)
library(janitor)
library(stargazer)
```

## Question 1

### Part b)

```{r}
# Read in the new corrected data (has all the countries), rename some stuff, rename the data frame
new.data = read_csv('corrected_ass_1_data.csv') %>% 
  rename(
    year = Year,
    dNNdt = `dN/Ndt  PerCap Pop Growth Rate (corrected)`,
    country = `Country/Aggregate`,
    population = Population,
    calories_pd = `Food: Daily Per Capita KCal`,
    GDP_pc = `PerCapita GDP`,
    HIV_prev = `HIv Prevalence (% Ages 15-49) (WHO)`,
    years_ed = `Mean Years of Education (Interpolated from Barro & Lee 2010)`
  ) %>% 
  mutate(
    dNNdt = dNNdt*2.303
  )
raw.data <- new.data
```

```{r}
# Only data for the years 1963 and 1964
data.63.64 <- raw.data %>% 
  filter(
    year %in% c(1963,1964)
  )
```

```{r}
# Calculating dN/Ndt by using the equalities r = dN/Ndt and r = ln(Nt+1/Nt)
pop.vector <- data.63.64$population # Pairs are: Argentina, Canada, China, India, Kenya, Mexico, South Korea
nt.indx <- c(1,3,5,7,9,11,13)
ntplus.indx <- c(2,4,6,8,10,12,14)
ratio.vector <- pop.vector[ntplus.indx]/pop.vector[nt.indx]
r.vector <- log(ratio.vector)
```

```{r}
# Make a data frame comparing the calculated dN/Ndt values to the given ones
data.q2 <- data.63.64 %>% 
  filter(
    year %in% c(1963)
  )

result.q2 <- tibble(cntry = data.q2$country, given = data.q2$dNNdt, calc = r.vector)
```

### part c)

```{r}
# Do this for all years of Kenya
data.kenya <- raw.data %>% 
  filter(
    country %in% c('Kenya')
  )

k.pop.vector <- data.kenya$population 
nt.indx <- seq(from = 1, to = 45, by = 1)
ntplus.indx <- seq(from = 2, to = 46, by = 1)
k.ratio.vector <- k.pop.vector[ntplus.indx]/k.pop.vector[nt.indx]
k.r.vector <- log(k.ratio.vector)
```

```{r}
# Graph the Kenya results
given.k.vec <- data.kenya$dNNdt
given.k.dnndt.vec <- given.k.vec[nt.indx]
graph.df <- tibble(gvn = given.k.dnndt.vec,calc = k.r.vector)
ggplot(data = graph.df, aes(x = gvn, y = calc))+
  geom_point(cex = 3)+
  geom_abline(intercept = 0, slope = 1, lty = 2) +
  scale_x_continuous(limits = c(0.025, 0.04)) +
  scale_y_continuous(limits = c(0.025, 0.04)) + 
  labs(title = 'Kenya - dN/Ndt: Given vs. Calculated',
       x = 'dN/Ndt Given',
       y = 'dN/Ndt Calculated')
```

## Question 2

### Part a)

```{r}
# Facet wrapped by country dN/Ndt vs Nt 
ggplot(data = raw.data, aes(x = population, y = dNNdt, color = country)) +
  geom_point() +
  facet_wrap(~country, scales = 'free') + 
  labs(x = 'Population',
       y = 'dN/Ndt',
       color = 'Country',
       title = 'Population vs. dN/Ndt, Faceted by Country')
```

### Part b)

```{r}
# Isolate data for one Asian and one Latin American country
asian.latin.df <- raw.data %>% 
  filter(
    country %in% c('Mexico', 'South Korea')
  ) %>% 
  mutate(
    dNdt = dNNdt*population
  )

# Lets check them out
# ggplot(data = asian.latin.df, aes(x = population, y = dNNdt, color = country)) +
#   geom_point() +
#   facet_wrap(~country, scales = 'free')
```

```{r}
# Looks good to me
# Let's figure out what carrying capacity is
# First isolate data from each country
mexico.df <- raw.data %>% 
  filter(
    country %in% c('Mexico')
  )
skr.df <- raw.data %>% 
  filter(
    country %in% c('South Korea')
  )

# Then, fit a linear model where population predicts dN/Ndt
# The population that gives you dN/Ndt = 0 is your K
# We can find this by solving y = mx + b for the x such that y = 0, which works out to be x = -b/m

# Fitting a linear model where dN/Ndt = m*population + b
lm.mx <- lm(dNNdt ~ population, data = mexico.df)
lm.skr <- lm(dNNdt ~ population, data = skr.df)

# x      =          -         b           /          m
k.mx <- as.numeric((-lm.mx$coefficients[1]/lm.mx$coefficients[2]))
k.skr <- as.numeric((-lm.skr$coefficients[1]/lm.skr$coefficients[2]))
```

```{r}
# Now that we've got out results, lets plot them for each country!
# Mexico first
ggplot(data = mexico.df, aes(x = population, y = dNNdt, color = year, size = calories_pd)) + 
  geom_point() +
  geom_abline(intercept = lm.mx$coefficients[1], slope = lm.mx$coefficients[2],
              lty = 2,
              color = 'red') + 
  scale_y_continuous(limits = c(0,0.035)) + 
  scale_x_continuous(limits = c(3*10^7, 15*10^7)) + 
  annotate("pointrange", 
           x = k.mx, 
           y = 0, 
           ymin = 0, 
           ymax = 0.0045,
           colour = "red", 
           size = 0.75) +
   annotate("text",
           x = k.mx,
           y = 0.007,
           label = paste('Estimated K \n=', round( (k.mx/10^6),1 ), 'million'),
           size = 4) + 
  labs(x = 'Population',
       y = 'dN/Ndt',
       title = 'Mexico: Population vs. Per Capita Growth Rate',
       size = 'Per Capita \nDaily Calories',
       color = 'Year')

# And South Korea
ggplot(data = skr.df, aes(x = population, y = dNNdt, color = year, size = calories_pd)) + 
  geom_point() +
  geom_abline(intercept = lm.skr$coefficients[1], slope = lm.skr$coefficients[2],
              lty = 2,
              color = 'red') + 
  scale_y_continuous(limits = c(0,0.03)) + 
  scale_x_continuous(limits = c(2.5*10^7, 6*10^7)) + 
  annotate("pointrange", 
           x = k.skr, 
           y = 0, 
           ymin = 0, 
           ymax = 0.0045,
           colour = "red", 
           size = 0.75) +
   annotate("text",
           x = k.skr,
           y = 0.007,
           label = paste('Estimated K \n=', round( (k.skr/10^6),1 ), 'million'),
           size = 4) + 
  labs(x = 'Population',
       y = 'dN/Ndt',
       title = 'South Korea: Population vs. Per Capita Growth Rate',
       size = 'Per Capita \nDaily Calories',
       color = 'Year')
```


## Question 3

### Part a)

```{r}
# Make a linear regression model for all the countries using years or education and the base-10 logarithm of per capita calories per day
mlr.data <- raw.data %>% 
  select(dNNdt, years_ed, calories_pd) %>% 
  mutate(
    calories_pd = log10(calories_pd)
  )
all.mlr.mdl <- lm(dNNdt ~ years_ed + calories_pd, data = mlr.data)
```

### Part b)

```{r}
# Make a linear regression model for each of the seven the countries using years or education and the base-10 logarithm of per capita calories per day

# Argentina
arg.mlr.data <- raw.data %>% 
  filter(
    country %in% c('Argentina')
  ) %>% 
  select(dNNdt, years_ed, calories_pd) %>% 
  mutate(
    calories_pd = log10(calories_pd)
  )
arg.mlr.mdl <- lm(dNNdt ~ years_ed + calories_pd, data = arg.mlr.data)

# Canada
can.mlr.data <- raw.data %>% 
  filter(
    country %in% c('Canada')
  ) %>% 
  select(dNNdt, years_ed, calories_pd) %>% 
  mutate(
    calories_pd = log10(calories_pd)
  )
can.mlr.mdl <- lm(dNNdt ~ years_ed + calories_pd, data = can.mlr.data)

# China
prc.mlr.data <- raw.data %>% 
  filter(
    country %in% c('China')
  ) %>% 
  select(dNNdt, years_ed, calories_pd) %>% 
  mutate(
    calories_pd = log10(calories_pd)
  )
prc.mlr.mdl <- lm(dNNdt ~ years_ed + calories_pd, data = prc.mlr.data)

# India
ind.mlr.data <- raw.data %>% 
  filter(
    country %in% c('India')
  ) %>% 
  select(dNNdt, years_ed, calories_pd) %>% 
  mutate(
    calories_pd = log10(calories_pd)
  )
ind.mlr.mdl <- lm(dNNdt ~ years_ed + calories_pd, data = ind.mlr.data)

# Kenya
ken.mlr.data <- raw.data %>% 
  filter(
    country %in% c('Kenya')
  ) %>% 
  select(dNNdt, years_ed, calories_pd) %>% 
  mutate(
    calories_pd = log10(calories_pd)
  )
ken.mlr.mdl <- lm(dNNdt ~ years_ed + calories_pd, data = ken.mlr.data)

# Mexico
mex.mlr.data <- raw.data %>% 
  filter(
    country %in% c('Mexico')
  ) %>% 
  select(dNNdt, years_ed, calories_pd) %>% 
  mutate(
    calories_pd = log10(calories_pd)
  )
mex.mlr.mdl <- lm(dNNdt ~ years_ed + calories_pd, data = mex.mlr.data)

# South Korea
skr.mlr.data <- raw.data %>% 
  filter(
    country %in% c('South Korea')
  ) %>% 
  select(dNNdt, years_ed, calories_pd) %>% 
  mutate(
    calories_pd = log10(calories_pd)
  )
skr.mlr.mdl <- lm(dNNdt ~ years_ed + calories_pd, data = skr.mlr.data)
```

```{r, results = 'asis'}
# Now we slap all the coefficients for all the linear models into a stargazer table so we can bullshit about them
stargazer(all.mlr.mdl, arg.mlr.mdl, can.mlr.mdl, prc.mlr.mdl, ind.mlr.mdl, ken.mlr.mdl, mex.mlr.mdl, skr.mlr.mdl,
          type = "html",
          column.labels = c('All Countries', 'Argentina', 'Canada', 'China', 'India', 'Kenya', 'Mexico', 'South Korea'),
          model.numbers = F,
          title = 'dN/Ndt Model Coefficients and Summary Statistics',
          covariate.labels = c('Years of Education',
                               'log10[Daily Calories]',
                               'Constant'),
          dep.var.labels = 'dN/Ndt')
```

